Pim\Bundle\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        username:
            - NotBlank:     ~
            - Length:
                min:        3
                max:        255
            - Pim\Bundle\UserBundle\Validator\Constraints\ValueShouldNotContainsBlacklistedCharacters: ~
        email:
            - NotBlank:     ~
            - Length:
                min:        6
                max:        255
            - Regex:
                pattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*))@([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}$/
                message: This value is not a valid email address.
        plainPassword:
            - NotBlank:
                groups:     [Registration]
            - Length:
                min:        2
        enabled:
            - NotNull:      ~
        roles:
            - Count:
                min:        1
                minMessage: "You must select at least {{ limit }} role"
                groups:     [User]
        namePrefix:
            - Pim\Bundle\UserBundle\Validator\Constraints\ValueShouldNotContainsBlacklistedCharacters: ~
        firstName:
            - NotBlank:     ~
            - Length:
                max:        100
            - Pim\Bundle\UserBundle\Validator\Constraints\ValueShouldNotContainsBlacklistedCharacters: ~
        middleName:
            - Pim\Bundle\UserBundle\Validator\Constraints\ValueShouldNotContainsBlacklistedCharacters: ~
        lastName:
            - NotBlank:     ~
            - Length:
                max:        100
            - Pim\Bundle\UserBundle\Validator\Constraints\ValueShouldNotContainsBlacklistedCharacters: ~
        nameSuffix:
            - Pim\Bundle\UserBundle\Validator\Constraints\ValueShouldNotContainsBlacklistedCharacters: ~
        birthday:
            - Date:         ~
        imageFile:
            - Image:        ~

Oro\Bundle\UserBundle\Entity\Role:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: label
    properties:
        label:
            - NotBlank:     ~
            - Length:
                max:        25

Oro\Bundle\UserBundle\Entity\Group:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max:        30
#        roles:
#            - Count:
#                min:        1
#                minMessage: "You must select at least {{ limit }} role"
